const actions = {

    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

    ADD_TEACHER_START: 'ADD_TEACHER_START',
    ADD_TEACHER_FAILURE: 'ADD_TEACHER_FAILURE',
    ADD_TEACHER_SUCCESS: 'ADD_TEACHER_SUCCESS',

};

export default actions;