const actions = {
    // POST_SIGN_UP: 'POST_SIGN_UP',
    // PRE_SIGNUP: 'PRE_SIGNUP',
    // PRE_SIGNUP_FAILURE: 'PRE_SIGNUP_FAILURE',
    // POST_SIGN_UP_FAILURE: 'POST_SIGN_UP_FAILURE',
    
    // Login actions
    LOGIN_START: 'LOGIN_START',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    // Signup actions
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    // Load user actions
    LOAD_USER_START: 'LOAD_USER_START',
    LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',
    LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
    
    // Get user profile actions
    GET_PROFILE_START: 'GET_PROFILE_START',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',

    // Logout action
    LOGOUT: 'LOGOUT',

    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_ERROR: 'UPDATE_PASSWORD_ERROR',

    // UPDATE_PROFILE: 'UPDATE_PROFILE',
    // UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
    // ADD_CAT: 'ADD_CAT',
    // ADD_CAT_ERROR: 'ADD_CAT_ERROR',
    // GET_CATEGORY: 'GET_CATEGORY',
    // GET_CATEGORY_ERROR: 'GET_CATEGORY_ERROR',
    // FORGET_PASS: 'FORGET_PASS',
    // RESET_FORGET_PASS: 'RESET_FORGET_PASS',
    // SUBMIT_APPROVAL: 'SUBMIT_APPROVAL',
    // CLEAR_EMAIL: 'CLEAR_EMAIL',
    // CLEAR_ERROR: 'CLEAR_ERROR',
}

export default actions;