const actions = {

    FETCH_EXAMS_START: 'FETCH_EXAMS_START',
    FETCH_EXAMS_FAILURE: 'FETCH_EXAMS_FAILURE',
    FETCH_EXAMS_SUCCESS: 'FETCH_EXAMS_SUCCESS',

    CREATE_EXAM_START: 'CREATE_EXAM_START',
    CREATE_EXAM_FAILURE: 'CREATE_EXAM_FAILURE',
    CREATE_EXAM_SUCCESS: 'CREATE_EXAM_SUCCESS',
    
    DELETE_EXAM_START: 'DELETE_EXAM_START',
    DELETE_EXAM_FAILURE: 'DELETE_EXAM_FAILURE',
    DELETE_EXAM_SUCCESS: 'DELETE_EXAM_SUCCESS',

    FETCH_RECORDS_START: 'FETCH_RECORDS_START',
    FETCH_RECORDS_FAILURE: 'FETCH_RECORDS_FAILURE',
    FETCH_RECORDS_SUCCESS: 'FETCH_RECORDS_SUCCESS',
    
    START_EXAM: 'START_EXAM',
    END_EXAM: 'END_EXAM',

    FETCH_QUESTIONS_START: 'FETCH_QUESTIONS_START',
    FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',

    SUBMIT_ANSWERS_START: 'SUBMIT_ANSWERS_START',
    SUBMIT_ANSWERS_FAILURE: 'SUBMIT_ANSWERS_FAILURE',
    SUBMIT_ANSWERS_SUCCESS: 'SUBMIT_ANSWERS_SUCCESS',

    // DELETE_USER_START: 'DELETE_USER_START',
    // DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    // DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

    // CREATE_USER_START: 'CREATE_USER_START',
    // CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    // CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

    // ADD_TEACHER_START: 'ADD_TEACHER_START',
    // ADD_TEACHER_FAILURE: 'ADD_TEACHER_FAILURE',
    // ADD_TEACHER_SUCCESS: 'ADD_TEACHER_SUCCESS',

};

export default actions;